### ISSUE TITLE
Add new enquiries webhooks topics

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3800]
We should build on our existing webhooks offering by offering more granular, domain type events.

- enquiries.created
- enquiries.accepted
- enquiries.rejected

**Tasks**

- [x] Update database event handler
- [x] Update CDC task template with new table selection rules
- [x] Update existing CDC tasks with new table selection rules
- [x] Update bulk indexing functionality to include new service
- [x] Add new topics to webhooks topic options

Do concurrently with #3806  as the CDC tasks have to be stopped to apply the new selection rules

**Comment by plittlewood-rpt** [comment]
PR 3737 opened to update indexing service

**Comment by plittlewood-rpt** [comment]
PR 3738 opened to update event handler

**Comment by plittlewood-rpt** [comment]
Now blocked by #3926

**Comment by plittlewood-rpt** [comment]
Omitted the granular topics hence reopening ticket. PR 4045 to add these
