### ISSUE TITLE
Add new documents webhooks topics

### ISSUE THREAD

**Issue by cbryanreapit** [reapit/foundations#3806]
We should build on our existing webhooks offering by offering more hooks. A documents webhook has been identified as a potentially useful set of topics for our partners. 

- documents.created
- documents.modified

**Tasks**

- [x] Update database event handler
- [x] Update CDC task template with new table selection rules
- [x] Update existing CDC tasks with new table selection rules
- [x] Update bulk indexing functionality to include new service
- [x] Add new topics to webhooks topic options

Do concurrently with #3800 as the CDC tasks have to be stopped to apply the new selection rules

**Comment by plittlewood-rpt** [comment]
PR 3727 opened to update event handler lambda

**Comment by plittlewood-rpt** [comment]
PR 3728 to update bulk indexing service and associated CF templates

**Comment by plittlewood-rpt** [comment]
Release two PRs above to production

**Comment by plittlewood-rpt** [comment]
Now blocked by #3926
