### ISSUE TITLE
Resolve issues with S3 pre-signed URL file downloads

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#7600]
**Background context**
We have previously tried to release an update to the documents service to force all file downloads from S3 to redirect to pre-signed URLs to relieve pressure on the service which currently copies files into memory before streaming them back out to the consumer. In addition, larger files cannot be downloaded in this manner due to technical payload max size limitations

**Specification**
- Project: Reapit.Services.Documents
- Understand what additional CORS requirements there are for customer S3 buckets to allow the work done in #7525  to be re-released
- The two options here are to use a staging bucket (that we control) and copy files into this bucket before downloading. There could be cost implications to this which we should understand, or work with SI to enable CORS on customer S3 buckets
- We should be able to use the Sales account and the AML app to replicate this problem
- As we have had a failed release we should ensure that we can roll this change out in a more controlled fashion (to Sandbox first, and then to all customers) so implement some kind of whitelist

**Tasks**
- [x] Liaise with SI team to understand CORS requirements - PL messaged PN 01/09
- [x] Make decision about which route to take (enable CORS on customer buckets, or copy file to staging bucket - preferably not using the service itself as a conduit - it's likely files can be transferred directly with the SDK)
- [x] Implement decided solution and re-release for SBOX
- [x] Release change wholesale
- [x] Please update #7576 when this goes out to notify developer that this functionality is available

**Comment by plittlewood-rpt** [comment]
Carried to next dev cycle - progress is being made on this ticket however there's some infrastructure adjustments we need to make at the same time which haven't yet been mapped out fully.
